// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0tscLDLAcuAK6p8E6reC0TU9C3p0Mew',
    appId: '1:977431736891:web:4cd21218c16e6a85d6a21e',
    messagingSenderId: '977431736891',
    projectId: 'sabjitaja-45326',
    authDomain: 'sabjitaja-45326.firebaseapp.com',
    storageBucket: 'sabjitaja-45326.appspot.com',
    measurementId: 'G-8YX2Y5E2PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1v_ZOALBKk2LwD-o5jOD-oNXeRVng_1s',
    appId: '1:977431736891:android:d4fbad815610c044d6a21e',
    messagingSenderId: '977431736891',
    projectId: 'sabjitaja-45326',
    storageBucket: 'sabjitaja-45326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGvh096CGe_BZmO1TOXTyM4ETCLNkY8k',
    appId: '1:977431736891:ios:8ea30622ca2b8b65d6a21e',
    messagingSenderId: '977431736891',
    projectId: 'sabjitaja-45326',
    storageBucket: 'sabjitaja-45326.appspot.com',
    androidClientId: '977431736891-ceh3v6ldk7o9tmlbsgqvu201a3e74tp5.apps.googleusercontent.com',
    iosClientId: '977431736891-nipu1apn0bah87ch9akprd5uipee53si.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelEcommerce',
  );
}
